# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QFont

from pygments.styles import get_all_styles

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 769)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main = QtWidgets.QHBoxLayout()
        self.main.setObjectName("main")
        self.sidebar = QtWidgets.QVBoxLayout()
        self.sidebar.setObjectName("sidebar")
        self.explorer = QtWidgets.QListWidget(parent=self.centralwidget)
        self.explorer.setObjectName("explorer")
        self.sidebar.addWidget(self.explorer)
        self.output = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.output.setDocumentTitle("")
        self.output.setReadOnly(True)
        self.output.setPlaceholderText("")
        self.output.setObjectName("output")
        self.sidebar.addWidget(self.output)
        self.run_code_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.run_code_button.setObjectName("run_code_button")
        self.sidebar.addWidget(self.run_code_button)
        self.clear_output_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_output_button.setObjectName("clear_output_button")
        self.sidebar.addWidget(self.clear_output_button)
        self.main.addLayout(self.sidebar)
        self.tab_bar = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_bar.setObjectName("tab_bar")
        self.main.addWidget(self.tab_bar)
        self.main.setStretch(1, 5)
        self.gridLayout.addLayout(self.main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuThemes = QtWidgets.QMenu(parent=self.menubar)
        self.menuThemes.setObjectName("menuThemes")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClose = QtGui.QAction(parent=MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)


        for theme in get_all_styles():
            self.menuThemes.addAction(theme)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuThemes.menuAction())


        self.retranslateUi(MainWindow)
        self.tab_bar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shibuh IDE"))
        __sortingEnabled = self.explorer.isSortingEnabled()
        self.explorer.setSortingEnabled(False)
        self.explorer.setSortingEnabled(__sortingEnabled)
        self.output.setFont(QFont("Iosevka", 16))
        self.run_code_button.setText(_translate("MainWindow", "Run code"))
        self.clear_output_button.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuThemes.setTitle(_translate("MainWindow", "Themes"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
